/** Countries with dial codes, for the careers application form. UAE first. */
export type Country = { name: string; dial: string; flag: string }

export const COUNTRIES: Country[] = [
  { name: 'United Arab Emirates', dial: '+971', flag: '🇦🇪' },
  { name: 'Saudi Arabia', dial: '+966', flag: '🇸🇦' },
  { name: 'Qatar', dial: '+974', flag: '🇶🇦' },
  { name: 'Bahrain', dial: '+973', flag: '🇧🇭' },
  { name: 'Kuwait', dial: '+965', flag: '🇰🇼' },
  { name: 'Oman', dial: '+968', flag: '🇴🇲' },
  { name: 'Argentina', dial: '+54', flag: '🇦🇷' },
  { name: 'Australia', dial: '+61', flag: '🇦🇺' },
  { name: 'Austria', dial: '+43', flag: '🇦🇹' },
  { name: 'Bangladesh', dial: '+880', flag: '🇧🇩' },
  { name: 'Belgium', dial: '+32', flag: '🇧🇪' },
  { name: 'Brazil', dial: '+55', flag: '🇧🇷' },
  { name: 'Canada', dial: '+1', flag: '🇨🇦' },
  { name: 'China', dial: '+86', flag: '🇨🇳' },
  { name: 'Czechia', dial: '+420', flag: '🇨🇿' },
  { name: 'Denmark', dial: '+45', flag: '🇩🇰' },
  { name: 'Egypt', dial: '+20', flag: '🇪🇬' },
  { name: 'Finland', dial: '+358', flag: '🇫🇮' },
  { name: 'France', dial: '+33', flag: '🇫🇷' },
  { name: 'Germany', dial: '+49', flag: '🇩🇪' },
  { name: 'Greece', dial: '+30', flag: '🇬🇷' },
  { name: 'Hong Kong', dial: '+852', flag: '🇭🇰' },
  { name: 'Hungary', dial: '+36', flag: '🇭🇺' },
  { name: 'India', dial: '+91', flag: '🇮🇳' },
  { name: 'Indonesia', dial: '+62', flag: '🇮🇩' },
  { name: 'Ireland', dial: '+353', flag: '🇮🇪' },
  { name: 'Italy', dial: '+39', flag: '🇮🇹' },
  { name: 'Japan', dial: '+81', flag: '🇯🇵' },
  { name: 'Jordan', dial: '+962', flag: '🇯🇴' },
  { name: 'Kenya', dial: '+254', flag: '🇰🇪' },
  { name: 'Lebanon', dial: '+961', flag: '🇱🇧' },
  { name: 'Malaysia', dial: '+60', flag: '🇲🇾' },
  { name: 'Mexico', dial: '+52', flag: '🇲🇽' },
  { name: 'Morocco', dial: '+212', flag: '🇲🇦' },
  { name: 'Nepal', dial: '+977', flag: '🇳🇵' },
  { name: 'Netherlands', dial: '+31', flag: '🇳🇱' },
  { name: 'New Zealand', dial: '+64', flag: '🇳🇿' },
  { name: 'Nigeria', dial: '+234', flag: '🇳🇬' },
  { name: 'Norway', dial: '+47', flag: '🇳🇴' },
  { name: 'Pakistan', dial: '+92', flag: '🇵🇰' },
  { name: 'Philippines', dial: '+63', flag: '🇵🇭' },
  { name: 'Poland', dial: '+48', flag: '🇵🇱' },
  { name: 'Portugal', dial: '+351', flag: '🇵🇹' },
  { name: 'Romania', dial: '+40', flag: '🇷🇴' },
  { name: 'Russia', dial: '+7', flag: '🇷🇺' },
  { name: 'Singapore', dial: '+65', flag: '🇸🇬' },
  { name: 'South Africa', dial: '+27', flag: '🇿🇦' },
  { name: 'South Korea', dial: '+82', flag: '🇰🇷' },
  { name: 'Spain', dial: '+34', flag: '🇪🇸' },
  { name: 'Sri Lanka', dial: '+94', flag: '🇱🇰' },
  { name: 'Sweden', dial: '+46', flag: '🇸🇪' },
  { name: 'Switzerland', dial: '+41', flag: '🇨🇭' },
  { name: 'Thailand', dial: '+66', flag: '🇹🇭' },
  { name: 'Tunisia', dial: '+216', flag: '🇹🇳' },
  { name: 'Türkiye', dial: '+90', flag: '🇹🇷' },
  { name: 'Ukraine', dial: '+380', flag: '🇺🇦' },
  { name: 'United Kingdom', dial: '+44', flag: '🇬🇧' },
  { name: 'United States', dial: '+1', flag: '🇺🇸' },
  { name: 'Vietnam', dial: '+84', flag: '🇻🇳' },
]

/** Dial codes, de-duplicated, for the phone prefix select. */
export const DIAL_CODES = COUNTRIES.filter(
  (c, i, all) => all.findIndex((o) => o.dial === c.dial) === i,
)
